### ISSUE TITLE
CL_MEM_OBJECT_ALLOCATION_FAILURE on Nvidia GTX1070

### ISSUE THREAD

**Issue by speryt** [shilch/fastmerkle#2]
I had to change merkle input argument types in merkle.cl 

```
diff --git a/merkle.cl b/merkle.cl
index af4de86..f47b2da 100644
--- a/merkle.cl
+++ b/merkle.cl
@@ -233,7 +233,7 @@ static void sha256d_cat(global const uint* lhs, global const uint* rhs, global u

 #define EQUAL(lhs, rhs) (lhs[0] == rhs[0] && lhs[1] == rhs[1] && lhs[2] == rhs[2] && lhs[3] == rhs[3] && lhs[4] == rhs[4] && lhs[5] == rhs[5] && lhs[6] == rhs[6] && lhs[7] == rhs[7])

-kernel void merkle(global const uchar* data, const size_t leaves, const size_t round, global int* mutated){
+kernel void merkle(global const uchar* data, const ulong leaves, const ulong round, global int* mutated){
     size_t id = get_global_id(0);
     size_t size = get_global_size(0);
```
to be able to even start on GTX1070, because size_t is apparently restricted type from input arguments. `ulong` is required instead of `uint` because of CL_INVALID_ARG_SIZE error.

Unfortunately, this fix only partially helps (btw - still works for integrated GPU on my Intel CPU), because on **8388608** leaves I'm getting CL_MEM_OBJECT_ALLOCATION_FAILURE error. I'm guessing that some other values/data types should also be changed to `ulong`, but I'm not an expert in OpenCL and not sure what else should be changed.

**Comment by shilch** [comment]
Hi,
I'll publish a fix for the `size_t` error (it affects all NVIDIA GPUs).  
I guess that you're getting CL_MEM_OBJECT_ALLOCATION_FAILURE because the host os ran out of memory to allocate the clBuffer. Are you running Windows? People have reported that when running on Linux, the error is gone.

**Comment by speryt** [comment]
Thanks for update, that will help a lot.
I'm running on Linux (Ubuntu 18.04)

**Comment by speryt** [comment]
Thanks for fix. That will help a lot.
I'm running Linux (Ubuntu 18.04).

**Comment by shilch** [comment]
Mmh, that's weird. Are you running the software in benchmark or in custom mode? Check the readme:

> Sometimes, the operating system has issues freeing memory fast enough (the benchmark consumes a lot) in which case it crashes the program.
You can just run ./fastmerkle custom (.\fastmerkle.exe custom on Windows) and enter the number 33554432 to do one single iteration of hashing a 13.5GB block. That's the most interesting time to know.

**Comment by speryt** [comment]
Ok, you are right. That helps. So in other words I can do benchmark step-by-step :) Thanks for help!
